In [2]:
import torch
import torch.nn.functional as F

torch.manual_seed(1)

In [3]:
# z = Wx+B

z = torch.FloatTensor([1, 2, 3])
hypothesis = F.softmax(z, dim=0)
hypothesis

tensor([0.0900, 0.2447, 0.6652])

In [4]:
z = torch.rand(3, 5, requires_grad=True) # 임의의 3x5 행렬 => class가 5개인 경우
z

tensor([[0.7576, 0.2793, 0.4031, 0.7347, 0.0293],
        [0.7999, 0.3971, 0.7544, 0.5695, 0.4388],
        [0.6387, 0.5247, 0.6826, 0.3051, 0.4635]], requires_grad=True)

In [5]:
hypothesis = F.softmax(z, dim=1) # dim=1 방향으로 소프트맥스 함수를 적용한다는 의미!
hypothesis

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)

In [6]:
hypothesis.sum(dim=1)

tensor([1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)

In [9]:
y = torch.randint(5, (3, )).long() # 0~5 정수중 랜덤하게 3, size 
y

tensor([2, 1, 0])

In [10]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1)

# scatter(dim의 방향, y.unsqueeze(1) 변경할 y 의 위치, 변경할 위치)
# 즉 y의 size(3, ) 에서 y.unsqueeze(1) Dim 1 방향에 1추가 ==> (3, 1)로 만든다.
# y.unsqueeze(1) => 3,1 size로 만들기


# y를 

tensor([[0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])

In [11]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
cost

tensor(1.6682, grad_fn=<MeanBackward0>)