# nn.Module 로 선형회귀 구현하기

앞서 세웠던 `W*x +b` 와 cost function 을 직접 구현했으나, 이미 구현되어 있는 모듈을 불러와 더 쉽게 선형 회귀 모델을 구현할 수 있다.

`nn.Linear()`

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# seed 고정

torch.manual_seed(42)


## 단순선형회귀 구현하기

### 1. 데이터

In [13]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

### 2. 모델 선언

In [3]:
model = nn.Linear(1, 1) # input_dim=1, output_dim=1 : 단순 선형회귀 이므로

In [5]:
print(list(model.parameters()))

# W, b 에 대한 초기값, 가변

[Parameter containing:
tensor([[0.7645]], requires_grad=True), Parameter containing:
tensor([0.8300], requires_grad=True)]


optimizer 설정

1) `import torch.optim as optim` 하여 `optim.SGD`으로 사용
2) `import torch` 하여 `torch.optim.SGD` 로 사용

In [6]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

### 3. model fit

In [9]:
nb_epochs = 2000

for epoch in range(nb_epochs):

    # hypothesis 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # optimizer
    optimizer.zero_grad()
    cost.backward() # 정의한 cost 로 backward 계산
    optimizer.step() # update

    if epoch%100 == 0:
        print(f'Epoch : {epoch}/{nb_epochs} Cost:{cost.item():.6f}')


Epoch : 0/2000 Cost:0.223008
Epoch : 100/2000 Cost:0.001393
Epoch : 200/2000 Cost:0.000011
Epoch : 300/2000 Cost:0.000000
Epoch : 400/2000 Cost:0.000000
Epoch : 500/2000 Cost:0.000000
Epoch : 600/2000 Cost:0.000000
Epoch : 700/2000 Cost:0.000000
Epoch : 800/2000 Cost:0.000000
Epoch : 900/2000 Cost:0.000000
Epoch : 1000/2000 Cost:0.000000
Epoch : 1100/2000 Cost:0.000000
Epoch : 1200/2000 Cost:0.000000
Epoch : 1300/2000 Cost:0.000000
Epoch : 1400/2000 Cost:0.000000
Epoch : 1500/2000 Cost:0.000000
Epoch : 1600/2000 Cost:0.000000
Epoch : 1700/2000 Cost:0.000000
Epoch : 1800/2000 Cost:0.000000
Epoch : 1900/2000 Cost:0.000000


In [10]:
# 임의의 입력 4를 선언
new_var =  torch.FloatTensor([[4.0]])
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[8.]], grad_fn=<AddmmBackward0>)


In [12]:
print(list(model.parameters()))

# W ~ 2 이고, b ~0 이어야 잘 나온것

[Parameter containing:
tensor([[2.]], requires_grad=True), Parameter containing:
tensor([1.0725e-07], requires_grad=True)]


## 다중 선형회귀 구현하기

다중선형회귀라 함은 feature 의 개수가 늘어났을 뿐이다

- 단순 선형 회귀 : $y = w \times x + b$
- 다중 선형 회귀 : $y = w_{1} \times x_{1} + w_{2} \times x_{2} + w_{3} \times x_{3} + b$

### 1. 데이터 load

In [15]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

### 2. 모델구현

In [17]:
model = nn.Linear(3, 1) # input_feature(dim) = 3, output_dim = 1(by 선형회귀)
print(list(model.parameters())) # a

[Parameter containing:
tensor([[-0.2811,  0.3391,  0.5090]], requires_grad=True), Parameter containing:
tensor([-0.4236], requires_grad=True)]


In [18]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

### 3. 학습

In [23]:
nb_epochs = 2000

for epoch in range(nb_epochs):

    # hypothesis
    prediction = model(x_train)

    # cost
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 == 0:
       print(f'Epoch : {epoch}/{nb_epochs} Cost:{cost.item():.6f}')

Epoch : 0/2000 Cost:15328.947266
Epoch : 100/2000 Cost:6.825569
Epoch : 200/2000 Cost:6.518710
Epoch : 300/2000 Cost:6.227828
Epoch : 400/2000 Cost:5.952083
Epoch : 500/2000 Cost:5.690675
Epoch : 600/2000 Cost:5.442862
Epoch : 700/2000 Cost:5.207896
Epoch : 800/2000 Cost:4.985125
Epoch : 900/2000 Cost:4.773916
Epoch : 1000/2000 Cost:4.573637
Epoch : 1100/2000 Cost:4.383702
Epoch : 1200/2000 Cost:4.203583
Epoch : 1300/2000 Cost:4.032788
Epoch : 1400/2000 Cost:3.870767
Epoch : 1500/2000 Cost:3.717095
Epoch : 1600/2000 Cost:3.571372
Epoch : 1700/2000 Cost:3.433124
Epoch : 1800/2000 Cost:3.301940
Epoch : 1900/2000 Cost:3.177516


In [26]:
new_var = torch.FloatTensor([[73, 80, 75]])

pred_y = model(new_var)

print(f'예측값 {pred_y}')

예측값 tensor([[152.7481]], grad_fn=<AddmmBackward0>)
